got terraform profile working

diff --git a/bin/browser b/bin/browser
--- a/bin/browser
+++ b/bin/browser
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 
-if [[ -n ${BROWSER-} ]]; then
-	echo "ERROR: browser already called: ${BROWSER}" 1>&2
+if [[ -n ${_BROWSER-} ]]; then
+	echo "ERROR: browser already called: ${_BROWSER}" 1>&2
 	exit 1
 fi
 
-export BROWSER="$0"
+export _BROWSER="$0"
 
 function main {
 	case "${VSCODE_GIT_ASKPASS_MAIN-}" in
