generalize  cmd

diff --git a/bin/d b/bin/d
--- a/bin/d
+++ b/bin/d
@@ -3,6 +3,7 @@
 function main {
 	set -efu
 
+	local cmd="${1:-}"
 	case "${1:-}" in
 		aws)
 			shift
@@ -24,13 +25,17 @@ function main {
 					fi
 					;;
 				*)
-					echo "ERROR: aws${1:+ ${1}} not supported" 1>&2
+					echo "ERROR: ${cmd}${1:+ ${1}} not supported" 1>&2
 					return 1
 					;;
 			esac
 			;;
+		"")
+			echo "ERROR: missing command" 1>&2
+			return 1
+			;;
 		*)
-			echo "ERROR: $1 not supported" 1>&2
+			echo "ERROR: ${cmd} not supported" 1>&2
 			return 1
 			;;
 	esac
