bunch more m tasks for s6

diff --git a/.config/mise/tasks/restart b/.config/mise/tasks/restart
--- a/.config/mise/tasks/restart
+++ b/.config/mise/tasks/restart
@@ -13,19 +13,14 @@ fi
 
 case "$(basename "$(pwd)")" in
 	svc)
-		cd ..
-		mise run serve		
+		echo "ERROR: s6-svscandir restart not implemented" 1>&2
+		exit 1
 		;;
 	*)
-		if ! s6-svstat . >/dev/null 2>&1; then
-			cd $(pwd)/../../svc && mise run activate
-			while ! s6-svstat .; do
-				sleep 1
-			done
-		fi
-		s6-svc -u .
-		while ! s6-svstat . | grep ^up; do
+		s6-svc -d .
+		while ! s6-svstat . | grep ^down; do
 			sleep 1
 		done
+		mise run start
 		;;
 esac
diff --git a/.config/mise/tasks/stop b/.config/mise/tasks/stop
--- a/.config/mise/tasks/stop
+++ b/.config/mise/tasks/stop
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#MISE description="Start an s6 service"
+#MISE description="Stop an s6 service"
 #USAGE arg "path" help="Path to a service directory" default=""
 
 set -efu -o pipefail
@@ -14,17 +14,12 @@ fi
 case "$(basename "$(pwd)")" in
 	svc)
 		cd ..
-		mise run serve		
+		echo "ERROR: s6-svscandir stop not implemented" 1>&2
+		exit 1
 		;;
 	*)
-		if ! s6-svstat . >/dev/null 2>&1; then
-			cd $(pwd)/../../svc && mise run activate
-			while ! s6-svstat .; do
-				sleep 1
-			done
-		fi
-		s6-svc -u .
-		while ! s6-svstat . | grep ^up; do
+		s6-svc -d .
+		while ! s6-svstat . | grep ^down; do
 			sleep 1
 		done
 		;;
