feat: manage s6 from parent dir of svc (#177)
fixes #176

diff --git a/.config/mise/tasks/restart b/.config/mise/tasks/restart
--- a/.config/mise/tasks/restart
+++ b/.config/mise/tasks/restart
@@ -7,17 +7,21 @@ set -efu -o pipefail
 
 cd "${MISE_ORIGINAL_CWD}"
 
-if [[ -n "${usage_path}" ]]; then
-	cd "${usage_path}"
+if [[ -n ${usage_path} ]]; then
+	if test -d "svc/${usage_path}/."; then
+		cd "svc/${usage_path}"
+	elif test -d "${usage_path}"; then
+		cd "${usage_path}/."
+	fi
 fi
 
 case "$(basename "$(pwd)")" in
-	svc)
-		echo "ERROR: s6-svscandir restart not implemented" 1>&2
-		exit 1
-		;;
-	*)
-		mise run stop
-		mise run start
-		;;
+svc)
+	echo "ERROR: s6-svscandir restart not implemented" 1>&2
+	exit 1
+	;;
+*)
+	mise run stop
+	mise run start
+	;;
 esac
