feat: m pr to create a PR

diff --git a/.config/mise/tasks/work b/.config/mise/tasks/work
--- a/.config/mise/tasks/work
+++ b/.config/mise/tasks/work
@@ -10,9 +10,9 @@ while ! gh auth token >/dev/null; do
 done
 
 branch="$(gh issue view "${usage_thing}" --json number,title | jq -r '"\(.number)-\(.title)" | gsub("[^a-zA-Z0-9]+"; "-") | ascii_downcase')"
-if [[ -z "${branch}" ]]; then
-    echo "ERROR: can't find issue or branch ${thing}" 2>&1
-    exit 1
+if [[ -z ${branch} ]]; then
+	echo "ERROR: can't find issue or branch ${thing}" 2>&1
+	exit 1
 fi
 
 if git checkout -b "${branch}"; then
@@ -26,4 +26,7 @@ else
 	git pull
 fi
 
-(cd; make sync)
+(
+	cd
+	make sync
+)
